language: clojure

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.3"

sudo: false

before_script:
  - psql -c 'CREATE DATABASE overlord;' -U postgres
  - psql -f resources/database/schema.sql -U postgres overlord

script: CLOVERAGE_VERSION=1.0.4-SNAPSHOT DB_PASSWORD= lein cloverage --coveralls

after_script:
  - curl -F 'json_file=@target/coverage/coveralls.json' https://coveralls.io/api/v1/jobs

after_success:
  - coveralls

notifications:
  email:
    on_failure: change
